pub mod area_set;
pub mod commands;
pub mod grid_images;
pub mod lit;
pub mod lmo_loader;
pub mod lmo_types;
pub mod map_loader;
pub mod map_writer;
pub mod mapinfo;
pub mod obj_loader;
pub mod obj_writer;
pub mod rbo;
pub mod scene_model;
pub mod scene_obj;
pub mod scene_obj_info;
pub mod server_writer;
pub mod terrain;
pub mod texture;
pub mod workbench;

use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MapEntry {
    pub name: String,
    pub display_name: String,
    pub map_file: String,
    pub has_obj: bool,
    pub has_rbo: bool,
    pub width: i32,
    pub height: i32,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct BuildingEntry {
    pub id: u32,
    pub filename: String,
    pub display_name: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SceneEffectEntry {
    pub id: u32,
    pub filename: String,
    pub display_name: String,
    pub effect_type: u32,
    pub object_type: u32,
    pub play_time: f32,
    pub base_size: i32,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct TerrainTextureEntry {
    pub id: u8,
    pub path: String,
    pub file_name: String,
    pub preview_data_uri: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct MapMetadata {
    pub name: String,
    pub width: i32,
    pub height: i32,
    pub section_width: i32,
    pub section_height: i32,
    pub total_sections: u32,
    pub non_empty_sections: u32,
    pub total_tiles: u32,
    pub object_count: u32,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MapPlacementRecord {
    pub index: u32,
    pub obj_type: u8,
    pub obj_id: u32,
    pub kind: String,
    pub world_x: f32,
    pub world_y: f32,
    pub world_z: f32,
    pub yaw_angle: i16,
    pub scale: i16,
    pub display_name: Option<String>,
    pub asset_name: Option<String>,
    pub attach_effect_id: Option<i32>,
    pub distance: Option<f32>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MapPlacementSummary {
    pub total: u32,
    pub building_count: u32,
    pub effect_count: u32,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct MapPlacementPage {
    pub total: u32,
    pub offset: u32,
    pub limit: u32,
    pub items: Vec<MapPlacementRecord>,
}

#[cfg(test)]
mod rbo_summary_tests {
    use super::rbo::{parse_rbo_records, summarize_rbo_bytes};

    #[test]
    fn rbo_summary_parses_client_text_records_with_optional_header() {
        let bytes = b"\\\\ generated by PKO map editor\n26 118.2 14.2 0 -180 0 0 0 12.5\n316 23.6 23.9 0 75 0 0 0 2.25\n";

        let summary = summarize_rbo_bytes(bytes, bytes.len() as u64);

        assert!(summary.present);
        assert_eq!(summary.byte_len, bytes.len() as u64);
        assert_eq!(summary.record_count, 2);
        assert_eq!(summary.distinct_type_ids, vec![26, 316]);
        assert_eq!(summary.warning_count, 0);
        assert_eq!(summary.first_warning, None);
        let bounds = summary.bounds.expect("bounds");
        assert_eq!(bounds.min_x, 23.6);
        assert_eq!(bounds.max_x, 118.2);
        assert_eq!(bounds.min_y, 14.2);
        assert_eq!(bounds.max_y, 23.9);
        assert_eq!(bounds.min_z, 0.0);
        assert_eq!(bounds.max_z, 0.0);
        assert_eq!(summary.sample_records.len(), 2);
        let first = summary.sample_records[0];
        assert_eq!(first.type_id, 26);
        assert!((first.x - 118.2).abs() < 0.001);
        assert!((first.y - 14.2).abs() < 0.001);
        assert_eq!(first.z, 0.0);
        assert_eq!(first.yaw, -180.0);
        assert_eq!(first.terrain_height, 12.5);
        let second = summary.sample_records[1];
        assert_eq!(second.type_id, 316);
        assert!((second.x - 23.6).abs() < 0.001);
        assert!((second.y - 23.9).abs() < 0.001);
        assert_eq!(second.z, 0.0);
        assert_eq!(second.yaw, 75.0);
        assert_eq!(second.terrain_height, 2.25);
    }

    #[test]
    fn rbo_summary_reports_malformed_lines_without_rejecting_valid_records() {
        let bytes = b"bad line\n26 10 20 3 -180 0 0 0 4\n";

        let summary = summarize_rbo_bytes(bytes, bytes.len() as u64);

        assert!(summary.present);
        assert_eq!(summary.record_count, 1);
        assert_eq!(summary.warning_count, 1);
        assert_eq!(
            summary.first_warning.as_deref(),
            Some("line 1 has 2 fields; expected 9")
        );
    }

    #[test]
    fn rbo_records_preserve_indices_and_skip_malformed_lines() {
        let bytes = b"\\\\ generated by PKO map editor\nbad line\n26 118.2 14.2 0 -180 0 0 0 12.5\n316 23.6 23.9 1.5 75 0 0 0 2.25\n";

        let parsed = parse_rbo_records(bytes);

        assert_eq!(parsed.records.len(), 2);
        assert_eq!(parsed.warnings.len(), 1);
        assert_eq!(parsed.warnings[0], "line 2 has 2 fields; expected 9");
        assert_eq!(parsed.records[0].index, 0);
        assert_eq!(parsed.records[0].line_number, 3);
        assert_eq!(parsed.records[0].type_id, 26);
        assert!((parsed.records[0].x - 118.2).abs() < 0.001);
        assert!((parsed.records[0].y - 14.2).abs() < 0.001);
        assert_eq!(parsed.records[0].z, 0.0);
        assert_eq!(parsed.records[0].yaw, -180.0);
        assert_eq!(parsed.records[0].terrain_height, 12.5);
        assert_eq!(parsed.records[1].index, 1);
        assert_eq!(parsed.records[1].line_number, 4);
        assert_eq!(parsed.records[1].type_id, 316);
    }

    #[test]
    fn rbo_records_reject_non_finite_floats_as_warnings() {
        let bytes = b"26 NaN 14.2 0 -180 0 0 0 12.5\n316 23.6 23.9 1.5 75 0 0 0 2.25\n";

        let parsed = parse_rbo_records(bytes);

        assert_eq!(parsed.records.len(), 1);
        assert_eq!(parsed.records[0].index, 0);
        assert_eq!(parsed.records[0].line_number, 2);
        assert_eq!(parsed.records[0].type_id, 316);
        assert_eq!(parsed.warnings.len(), 1);
        assert_eq!(parsed.warnings[0], "line 1 field x is not a finite float");
    }
}
